server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # هذا السطر يوجه أي مسار فرعي إلى index.html ليعمل React Router بشكل صحيح
        try_files $uri $uri/ /index.html;
    }
}