version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - PGHOST=host.docker.internal
      - PGUSER=postgres
      - PGPASSWORD=00000
      - PGDATABASE=food_surplus_db
      - PGPORT=5432
      - JWT_SECRET=my_super_secret_key_123
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always